version: '3.8'
services:
  backend:
    build:
      context: ./PRJ_SERVICE_SPRING_BOOT_REACT
    ports:
      - "8080:8080"
    networks:
      - red-interna

  frontend:
    build:
      context: ./spring_boot_react_frontend
    ports:
      - "3000:80"
    networks:
      - red-interna
    depends_on:
      - backend

networks:
  red-interna:
    driver: bridge
